config/routes.rb
Rails.application.routes.draw do

  post '/pay/:slug', to: 'items#pay', as: :pay

  resources :books
  devise_for :users
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get 'pickup/:uuid', to: 'items#pickup', as: :pickup
end

app/views/pages/_books.html.erb
<table class="table">
        <thead>
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Available</th>
            <th scope="col"></th>
            <br>
            </tr>
        </thead>
        <tbody>
            
            <% @books.each do |book| %>
            <tr>
            <th scope="row">1</th>
            <td><%= book.id  %></td>
            <td><%= link_to book.name, book_path(book)  %></td>
            <td><%= book.availability  %></td>
            <td><%= link_to 'Edit', edit_book_path(book)  %></td>
             </tr>
            <% end %>
           
        </tbody>
    </table>

app/views/pages/_purchased.html.erb
<table class="table">
        <thead>
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col"></th>
            <br>
            </tr>
        </thead>
        <tbody>
            
            <% @purchased.each do |sale| %>
            <tr>
            <th scope="row">1</th>
            <td><%= link_to sale.book.name, pickup_path(sale.uuid)  %></td>
            <td><%= time_ago_in_words(sale.created_at) %> ago</td>
             </tr>
            <% end %>
           
        </tbody>
    </table>

app/views/pages/_sales.html.erb
<table class="table">
        <thead>
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Buyer</th>
            <th scope="col"></th>
            <br>
            </tr>
        </thead>
        <tbody>
            
            <% @sales.each do |sale| %>
            <tr>
            <th scope="row">1</th>
            <td><%= link_to sale.book.name, pickup_path(sale.uuid)  %></td>
            <td><%= time_ago_in_words(sale.created_at) %> ago</td>
            <td><%= sale.buyer_email%> ago</td>
             </tr>
            <% end %>
           
        </tbody>
    </table>

app/views/pages/dashboard.html.erb
<h3>Dashboard</h3>

<div class="row">
    <div class="col-md-4">
    <h3>Books
    <%= link_to 'New Book', 
    new_book_path, class: "btn btn-primary btn-sm"  %>
    </h3>
    <%= render 'books'  %>
    </div>

    <div class="col-md-4">
    <h3>Purchases</h3>
    <%= render 'purchased'  %>
    </div>

    <div class="col-md-4">
    <h3>Sales</h3>
    <%= render 'sales'  %>
    </div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>Welcome to eBook</h1>
<p>The Largest Bookstore in the World!</p>
<%= link_to "Books", books_path, class: 'btn btn-primary btn-lg' %>
<%= link_to "Sign_Up", new_user_registration_path, class: 'btn btn-primary btn-lg'  %>
</div>
<div class="row">
<%= render @books  %>
</div>