config/routes.rb
Rails.application.routes.draw do

  post '/pay/:slug', to: 'items#pay', as: :pay

  resources :books
  devise_for :users
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get 'pickup/:uuid', to: 'items#pickup', as: :pickup
end

app/models/book.rb
class Book < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    belongs_to :user
    has_many :sales
    has_attached_file :image
    has_attached_file :resource

    validates_attachment :image, presence: true,
    content_type: {content_type: ["image/jpeg", "image/gif", "image/jpg", "image/png" ]},
    message: 'Only images allowed'

    validates_attachment :resource, presence: true,
    content_type: {content_type:  "application/pdf"},
    message: "Only pdf allowed"

    validates_numericality_of :price,
    greater_than: 49, message: "Price must be at least 50 yen!"


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  # GET /books
  # GET /books.json
  def index
    @books = Book.all.where(availability:true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="card col-md-4 p-4">
    <%= image_tag book.image.url, class: "card-img-top"  %>
    <div class="card-body">
      <h5><strong><%= link_to book.name, book_path(book)  %></strong></h5>
      <p><%= book.price %>円</p>
    </div>
  </div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html:{class: 'form-signin'}) do |f| %>
  <%= f.error_notification %>
  
    <%= f.input :name, required: true, label: false, placeholder:"Name" %>
    <%= f.input :author, required: true, label: false, placeholder:"Author"  %>
    <%= f.input :description, required: true, label: false, placeholder:"Description"  %>
    <%= f.input :image  %>
    <%= f.input :resource  %>
      <%= f.input :price, required: true, label: false, placeholder:"Price"  %>
    <%= f.input :availability %>

    <%= f.button :submit, class:"btn btn-primary btn-block" %>
<% end %>

app/views/books/edit.html.erb
<h1 class="text-center">Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

      <div class="container">
      <div class="row">
      <%= render @books %>
      </div>
      </div>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
  <%= image_tag @book.image.url, class:"img-fluid"  %>
  </div>
  <div class="col-md-6">
  <h3><%= @book.name %> by <%= @book.author %></h3>
  <p><%= @book.description %></p>
 <p class="text-center"><strong><%= @book.price  %></strong>Japanese Yen</p>

 
  <% if current_user %>
   <%= form_tag buy_path(slug: @book.slug) do %>
   <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description= "<%= @book.name %>"
          data-name = "eBook"
          data-amount= "<%= @book.price %>"
          data-email="<%= current_user.email %>"
          data-locale="auto"></script>
  <% end %>
  <% else %>
  <p>Please log in to purchase this book</p>
  <% end %>
  

 <!--
   <%= form_tag pay_path(slug: @book.slug) do %>
  <script type="text/javascript"
    src="https://checkout.pay.jp"
    class="payjp-button"
    data-key="pk_test_0383a1b8f91e8a6e3ea0e2a9">
  </script>
<% end %>
-->

  </div>
</div>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>