config/routes.rb
Rails.application.routes.draw do

  post '/pay/:slug', to: 'items#pay', as: :pay

  resources :books
  devise_for :users
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get 'pickup/:uuid', to: 'items#pickup', as: :pickup
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to 'eBook', root_path, class:"navbar-brand"  %>
    <ul class="navbar-nav mr-auto">
    </ul>
     <ul class="nav navbar-nav">
     <li><%= link_to "Books|", books_path %></li>
     
     <% if current_user %>
     <li><%= link_to 'Log Out|', destroy_user_session_path, method: :delete  %></li>
     <li><%= link_to 'Dashboard|', dashboard_path %></li>
     <li><%= link_to 'Profile', edit_user_registration_path %></li>
     <% else %>
     <li><%= link_to 'Log In', new_user_session_path %></li>
     <% end  %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'  %>
  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
  <button class="close" data-dismiss="alert">X</button>
  <%= message  %>
  </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>